### ISSUE TITLE
Often unable to move in certain directions

### ISSUE THREAD

**Issue by skeeballz** [New-Club-Penguin/NewCP-App-Build#3]
Hi there! I just wanted to say that while I'm very much enjoying everything about NewCP as a CPR refugee, I've noticed from walking and especially while mining that sometimes I'm unable to walk in certain directions? My only guess is that the game has trouble registering clicks under a certain player threshold, but I've tested two separate mice as well as my laptop's touchpad. and the issue stands with all three. Any and all help is highly appreciated, thanks!

**Comment by iContinux** [comment]
Bug Reports are to be posted in the discord server, not here.
